apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tuf7l2dr8-go 
  janus-idp.io/tekton: tuf7l2dr8-go
  backstage.io/kubernetes-id: tuf7l2dr8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tuf7l2dr8-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml