apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tuf7l2dr8-go
  janus-idp.io/tekton: tuf7l2dr8-go
  backstage.io/kubernetes-id: tuf7l2dr8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tuf7l2dr8-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
